export const DIRECTIONS = {
  UP: "up",
  RIGHT: "right",
  DOWN: "down",
  LEFT: "left",
};

export const OPPOSITE_DIRECTION = {
  [DIRECTIONS.UP]: DIRECTIONS.DOWN,
  [DIRECTIONS.RIGHT]: DIRECTIONS.LEFT,
  [DIRECTIONS.DOWN]: DIRECTIONS.UP,
  [DIRECTIONS.LEFT]: DIRECTIONS.RIGHT,
};

export const DIRECTION_KEYS = {
  ArrowUp: DIRECTIONS.UP,
  w: DIRECTIONS.UP,
  k: DIRECTIONS.UP,
  ArrowDown: DIRECTIONS.DOWN,
  s: DIRECTIONS.DOWN,
  j: DIRECTIONS.DOWN,
  ArrowLeft: DIRECTIONS.LEFT,
  a: DIRECTIONS.LEFT,
  h: DIRECTIONS.LEFT,
  ArrowRight: DIRECTIONS.RIGHT,
  d: DIRECTIONS.RIGHT,
  l: DIRECTIONS.RIGHT,
};

export const BOARD_WIDTH = 20;
export const BOARD_HEIGHT = 15;
export const BOARD_SIZE = BOARD_WIDTH * BOARD_HEIGHT;
export const INITIAL_POSITION = 154;
export const MOVE_INTERVAL = 500;
export const INITIAL_FOOD_POSITION = 23;
export const SCORE_PER_FOOD = 10;